### PR TITLE
Add setting for CronJob apiVersion to support batch/v1 and batch/v1beta1

### PR DESCRIPTION
**Pull request by tuunit**
Kubernetes removed the support for the deprecated `batch/v1beta1` api implementation of CronJobs in v1.25 and promoted CronJobs to `batch/v1` back in v1.21. Therefore we currently cannot deploy CronJobs in up to date Kubernetes Clusters.

API promotion to `batch/v1` since: [Kubernetes v1.21](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#api-change-5)
Support cease notice: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25

### CODE REVIEW

**Comment by tuunit** [comment]
@raphabot how about the approach to change the apiVersion in the values.yaml and add the v1beta1 as the default to keep the backwards compatibility

**Comment by tuunit** [comment]
@raphabot furthermore the Trendmicro UI guide is incomplete as the override example forgets to mention that the auth.secretSeed is mandatory to be set
image

**Comment by tuunit** [comment]
@raphabot I've made an update to the implementation:

values.yaml and README.md
```yaml
kubernetes:
  cronjob:
    # The apiVersion is kept at `batch/v1beta1` to ensure backwards compatibility to kubernetes versions before v1.21
    # configure apiVersion `batch/v1` if you want to deploy the Deep Security Smart Check on kubernetes v1.25+
    #
    # Default value: batch/v1beta1
    apiVersion: batch/v1beta1
```

tasks.yaml
```yaml
{{ if .Values.tasks.scan.enabled }}
apiVersion: {{ .Values.kubernetes.cronjob.apiVersion }}
kind: CronJob
metadata:
```

**Comment by tuunit** [comment]
@raphabot any updates on this?

**Comment by dbrisson21** [comment]
> @raphabot any updates on this?

Hi @tuunit, release 1.2.80 uses the updated CronJob apiVersion ```batch/v1```. As a result, I believe this pull request can be closed?

**Comment by tuunit** [comment]
> > @raphabot any updates on this?
> 
> Hi @tuunit, release 1.2.80 uses the updated CronJob apiVersion `batch/v1`. As a result, I believe this pull request can be closed?

Okay good to see the change has been done.

**Pull request closed without merging**
